# Your name and what you do
name: Brennan Sullivan
bio: How do brains learn?

description: My online academic CV

# Profile picture
picture: assets/images/me.jpeg

# your url: http://USERNAME.github.io
url: https://brennanSullivan.github.io

# do you want to display social media links? true or false
social-media: true
# Add your username for the social media websites listed below
# If you don't have an account on any of them, comment out the line
# facebook: myfacebook
twitter: currentclamp
linkedin: sullivan-brennan
github: brennanSullivan
email: brennansullivan@bcm.edu
googlescholar: citations?user=4WC4CvsAAAAJ&hl=en

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: normal

# do you want to display an about section? true or false
about: true

# do you want to display a skills section? true or false
skills: false

# add your skills here
skills-list:
    - Languages - Python and Matlab
    - Libraries - Numpy, Pandas, Scipy, Scikit-learn 
    - Tools - MacOS, Jupyter Notebook, Git 

# do you want to display a projects section? true or false
projects: false

# add your projects here
project-list:
    KCC2:
        name: Targeting ischemia-induced KCC2 hypofunction rescues refractory neonatal seizures and mitigates epileptogenesis in a mouse model
        description: Neonatal seizures pose a clinical challenge in their early detection, acute management, and long-term comorbidities. They are often caused by hypoxic-ischemic encephalopathy and are frequently refractory to the first-line antiseizure medication phenobarbital. Our findings therefore validate KCC2 as a clinically relevant target for refractory neonatal seizures and provide insights for future drug development.
        url: https://www.science.org/doi/10.1126/scisignal.abg2648?url_ver=Z39.88-2003&rfr_id=ori:rid:crossref.org&rfr_dat=cr_pub%20%200pubmed
    World-Cup-History:
        name: World Cup  History
        description: npm package for FIFA World cup historical data
        url: https://github.com/jibolash/world-cup-history
    Tweeter:
        name: Tweeter
        description: A Twitter inspired web application built with Angular 5
        url: https://tweetermum.herokuapp.com
    Transcend:
        name: Transcend
        description: An android app for meditation and mindfulness
        url: https://github.com/Khosbayar/Transcend


# do you want to display the theme attribution? true or false
footer: false

# Enable animations? true or false
animation: true

gems:
  - jekyll-seo-tag

exclude: [README.md, Gemfile, Gemfile.lock, _site, Rakefile, travis.sh, vendor]
