# Your name and what you do
name: Brennan James Sullivan
bio: How do brains learn?

description: My online academic CV

# Profile picture
picture: assets/images/me.jpeg

# your url: http://USERNAME.github.io
url: https://brennanSullivan.github.io

# do you want to display social media links? true or false
social-media: true
# Add your username for the social media websites listed below
# If you don't have an account on any of them, comment out the line
# facebook: myfacebook
twitter: currentclamp
linkedin: sullivan-brennan
github: brennanSullivan
email: brennansullivan@bcm.edu
googlescholar: citations?user=4WC4CvsAAAAJ&hl=en
cv: https://brennanSullivan.github.io/brennansullivan.github.io/cv.pdf


# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: normal

# do you want to display an about section? true or false
about: true

# do you want to display a skills section? true or false
skills: false

# add your skills here
skills-list:
    - Languages - Python
    - Libraries - Numpy, Pandas, Scipy, Scikit-learn 
    - Tools - MacOS, Jupyter Notebook, Git, LaTeX

# do you want to display a projects section? true or false
papers-list: true


# do you want to display the theme attribution? true or false
footer: false

# Enable animations? true or false
animation: true

gems:
  - jekyll-seo-tag

exclude: [README.md, Gemfile, Gemfile.lock, _site, Rakefile, travis.sh, vendor]
